---

test_workflow_steps:
  - tox_description: 'create workload resources except test_manila_upgrade'
    tox_envlist: scenario
    tox_step_name: create_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: no
    pytest_addopts: "-k 'not test_manila_upgrade'"

  - tox_description: 'create manila upgrade test resources'
    tox_envlist: manila
    tox_step_name: create_manila_upgrade_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: no
    pytest_addopts: "-k test_manila_upgrade"

  - tox_description: 'verify workload resources except test_manila_upgrade'
    tox_envlist: scenario
    tox_step_name: verify_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: yes
    pytest_addopts: "-k 'not test_manila_upgrade'"

  - tox_description: 'verify manila upgrade test resources'
    tox_envlist: manila
    tox_step_name: verify_manila_upgrade_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: yes
    pytest_addopts: "-k test_manila_upgrade"
