---

test_workflow_steps:
  - tox_description: 'create manila resources'
    tox_envlist: manila
    tox_step_name: create_manila_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: no
    pytest_addopts: "-k 'not test_manila_upgrade'"

  - tox_description: 'create manila upgrade test resources'
    tox_envlist: manila
    tox_step_name: create_manila_upgrade_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: no
    pytest_addopts: "-k test_manila_upgrade"
