- project:
    templates:
      - ansible-role-jobs
      - build-openstack-docs-pti
      - build-release-notes-jobs-python3
      - check-requirements
      - devstack-tobiko
      - devstack-tobiko-functional
      - devstack-tobiko-nova
      - devstack-tobiko-octavia
      - devstack-tobiko-ovs
      - devstack-tobiko-storage
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-to-pypi
      - tobiko-infrared
      - tobiko-tox-py39
    vars:
        rtd_webhook_id: '84947'
    periodic:
      jobs:
        - requirements-check:
            voting: true
    check:
      jobs:
        - tobiko-tox-linters-py314
    gate:
      jobs:
        - tobiko-tox-linters-py314
    post:
      jobs:
        - tobiko-upload-git-mirror
    release:
      jobs:
        - tobiko-upload-git-mirror
    pre-release:
      jobs:
        - tobiko-upload-git-mirror

- job:
    name: tobiko-tox-linters-py314
    parent: openstack-tox-py314
    description: Run Tobiko linters with Python 3.14.
    voting: true
    vars:
      tox_envlist: linters
      tox_environment:
        TOX_PYTHON: python3.14
